config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'home#index'

  devise_for :users

  resources :businesses
  resources :compaigns, except: %i[index]

  get '/followups/:id', to: 'compaigns#followup', as: 'followup'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[show edit update destroy]

  def index
    @businesses = current_user.businesses
  end

  def show; end

  def new
    @business = Business.new
    @business.business_emails.build
    @business.services.build
  end

  def edit; end

  def create
    @business = current_user.businesses.new(business_params)

    if @business.save
      redirect_to business_url(@business), notice: 'Business was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @business.update(business_params)
      redirect_to business_url(@business), notice: 'Business was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @business.destroy

    redirect_to businesses_url, notice: 'Business was successfully destroyed.'
  end

  private

  def set_business
    @business = Business.find(params[:id])
  end

  def business_params
    params.require(:business).permit(:name, :tag_line, :website_url, :email, :encrypted_password,
                                     business_emails_attributes: %i[id _destroy email], services_attributes: %i[id _destroy name])
  end
end

app/views/businesses/_business_email_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">

  <%= f.label :business_email, class: "form-label" %>
  <div class="input-group mb-3">
    <%= f.text_field :email, placeholder: "Enter Business email", class: 'form-control', id: "inlineFormInputGroup" %>
     <div class="input-group-append">
      <div class="input-group-text rounded-start-0"><button type="button" data-action="nested-form#remove", class='btn btn-close'></button></div>
    </div>
  </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/businesses/_form.html.erb
<%= form_with(model: business, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } ) do |form| %>
  <%= render "shared/error_messages", object: business %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, placeholder: "Business Name", class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :tag_line, class: "form-label" %>
    <%= form.text_field :tag_line, placeholder: "Tag line of your business", class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :website_url, class: "form-label" %><em> (Optional)</em>
    <%= form.text_field :website_url, placeholder: "https://www.mywebsite.com", class: 'form-control' %>
  </div>

  <h6 class="text-center">Setup Email Configration</h6>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, placeholder: "example@gmail.com", class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :password, class: "form-label" %>
    <%= form.text_field :encrypted_password, placeholder: "your app password", class: 'form-control', required: true %>
  </div>

  <h6 class="text-center">Add services</h6>

  <%= form.fields_for :services do |service_fields| %>
    <%= render "service_form", f: service_fields %>
  <% end %>

  <template data-nested-form-target="template">
    <%= form.fields_for :services, Service.new, child_index: 'NEW_RECORD' do |service_fields| %>
      <%= render "service_form", f: service_fields %>
    <% end %>
  </template>
  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add", class="btn border btn-light">Add new service</button>

  <h6 class="text-center">Add Business Emails</h6>

  <%= form.fields_for :business_emails do |business_email_fields| %>
    <%= render "business_email_form", f: business_email_fields %>
  <% end %>

  <template data-nested-form-target="template">
    <%= form.fields_for :business_emails, BusinessEmail.new, child_index: 'NEW_RECORD' do |business_email_fields| %>
      <%= render "business_email_form", f: business_email_fields %>
    <% end %>
  </template>
  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add", class="btn border btn-light">Add new business email</button>


  <div class="text-center mt-2">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/businesses/_service_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">

  <%= f.label :service, class: "form-label" %>
  <div class="input-group mb-3">
    <%= f.text_field :name, placeholder: "Enter service name", class: 'form-control', id: "inlineFormInputGroup" %>
     <div class="input-group-append">
      <div class="input-group-text rounded-start-0"><button type="button" data-action="nested-form#remove", class='btn btn-close'></button></div>
    </div>
  </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/businesses/edit.html.erb
<div class="d-flex flex-column p-5 m-auto w-40rem mt-5 shadow">
  <h3 class="text-center">Update your business</h3>
  <%= render "form", business: @business %>
</div>

<br>

<div>
  <%= link_to "Show this business", @business %> |
  <%= link_to "Back to businesses", businesses_path %>
</div>

app/views/businesses/index.html.erb
<div><%= link_to "New business", new_business_path %></div>

<div class="d-flex flex-wrap p-5 gap-3 justify-content-center">
  <% @businesses.each do |business| %>
    <div class="border border-1">
      <div class="fs-5 fw-semibold p-4"><%= business.name %></div>
      <div class="p-4"> <%= link_to "Manage this business", business %> </div>
    </div>
  <% end %>
</div>

app/views/businesses/new.html.erb
<div class="d-flex flex-column p-5 m-auto w-40rem mt-5 shadow">
  <h3 class="text-center">Create your business</h3>
  <%= render "form", business: @business %>
</div>

<br>

<div>
  <%= link_to "Back to businesses", businesses_path %>
</div>

app/views/businesses/show.html.erb
<div class="p-3 d-flex flex-wrap justify-content-between">
  <div class="fs-4 fw-semibold"><%= @business.name %> | <%= @business.tag_line %></div>
  <div><%= link_to "New compaign", new_compaign_path(@business, business_id: @business.id) %></div>
</div>

<div class="m-5">
  <div class="fw-semibold">Listed business emails</div>
  <ul>
    <% @business.business_emails.each do |business_email| %>
      <li><%= business_email.email %></li>
    <% end %>
  </ul>
</div>

<div class="m-5">
  <div class="fw-semibold ">Compaigns: </div>
  <table class="table mt-3">
    <thead class="table-light">
      <tr>
        <td> Scheduled at </td>
        <td> Leads Count </td>
        <td> First Follow-up </td>
        <td> Second Follow-up </td>
        <td> Third Follow-up </td>
        <td> Fourth Follow-up </td>
        <td> Fifth Follow-up </td>
      </tr>
    </thead>
    <tbody>
      <% Compaign.where(service_id: @business.services.ids).each do |compaign| %>
        <tr class="border-bottom">
          <td> <%= compaign.scheduled_at.strftime("For %A %d-%b-%Y") %> </td>
          <td> 
            <div><%= compaign.leads_count %><div>
            <div><%= link_to "Show this compaign", compaign, class: "text-primary" %></div>
          </td>
          <% compaign.followups.each_with_index do |followup, i| %>
            <td> 
              <div><%= followup.sent_at.strftime("On %A %d-%b-%Y") %></div>
              <div><%= display_followup_status(followup, i+1 ) %></div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div>
  <%= link_to "Back to businesses", businesses_path %> |
  <%= link_to "Edit this business", edit_business_path(@business) %> |
  <%= button_to "Destroy this business", @business, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-light text-danger" %>
</div>