config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'home#index'

  devise_for :users

  resources :businesses
  resources :compaigns, except: %i[index]

  get '/followups/:id', to: 'compaigns#followup', as: 'followup'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/compaign.rb
class Compaign < ApplicationRecord
  validates :email_subject, :email_body, :leads_count, :scheduled_at, presence: true

  belongs_to :business_email
  belongs_to :service
  has_many :followups, dependent: :destroy
  has_many :processed_leads, dependent: :destroy

  accepts_nested_attributes_for :followups, reject_if: :all_blank, allow_destroy: true

  validate :max_followups_limit

  def business
    service.business
  end

  private

  def max_followups_limit
    return unless followups.size > 5

    errors.add(:followups, "can't exceed 5")
  end
end

app/controllers/compaigns_controller.rb
require 'csv'
class CompaignsController < ApplicationController
  before_action :set_compaign, only: %i[show edit update destroy]
  before_action :set_followup, :previous_followups_sent?, only: %i[followup]

  def show; end

  def new
    @business = Business.find(params[:business_id])
    @compaign = Compaign.new
    @compaign.followups.build
  end

  def create
    @compaign = Compaign.new(compaign_params)
    if validate_csv_headers(params[:compaign][:csv_file]) && @compaign.save
      CompaignsProcessingService.new({ compaign: @compaign, csv_file: params[:compaign][:csv_file],
                                       lead_params: }).call!
      redirect_to @compaign, notice: 'compaign was successfully created and is being processed'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @compaign.update(compaign_params)
      redirect_to @compaign, notice: 'compaign was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @compaign.destroy
    redirect_to @compaign.business, notice: 'compaign was successfully destroyed.'
  end

  def followup
    if !@followup.sent && FollowupService.new(@followup).call!
      redirect_to @followup.compaign, notice: 'Follow-up emails were successfully sent'
    else
      redirect_to @followup.compaign, alert: 'Problem sending follow-up emails'
    end
  end

  private

  def set_compaign
    @compaign = Compaign.find(params[:id])
  end

  def set_followup
    @followup = Followup.find(params[:id])
  end

  def compaign_params
    params.require(:compaign).permit(:business_email_id, :service_id, :scheduled_at, :email_subject, :email_body,
                                     followups_attributes: %i[id _destroy sent_at content])
  end

  def lead_params
    params.require(:compaign).permit('title_id', 'country_id', 'platform_id')
  end

  def previous_followups_sent?
    return unless @followup.compaign.followups.where('id < ?', @followup.id).exists?(sent: false)

    flash[:alert] = 'Cannot send followup until all previous followups are sent'
    redirect_to @followup.compaign
  end

  def validate_csv_headers(file)
    require_headers = %w[Name Email]

    CSV.foreach(file, headers: true) do |row|
      missing_headers = require_headers - row.headers
      return true unless missing_headers.any?

      @compaign.errors.add(:base, "Missing headers: #{missing_headers.join(', ')}")
      return false
    end
  end
end

app/helpers/compaigns_helper.rb
module CompaignsHelper
  def display_followup_status(followup, followup_count)
    if followup.sent
      content_tag(:span, 'sent', class: 'bg-success px-2 py-1 text-white rounded-1')
    else
      link_to "Send #{num_to_text(followup_count)} follow-up", followup_path(followup),
              class: 'text-success'
    end
  end

  private

  def num_to_text(num)
    case num
    when 1
      'first'
    when 2
      'second'
    when 3
      'third'
    when 4
      'fourth'
    when 5
      'fifth'
    end
  end
end

app/views/compaigns/_followup_form.html.erb
<div class="nested-form-wrapper border p-4 mb-3" data-new-record="<%= f.object.new_record? %>">

  <div class="text-end">
    <button type="button" data-action="nested-form#remove", class='btn btn-close'></button>
  </div>

  <div class="mb-3">
    <label class="form-label text-muted">Content</label>
    <% default_content = f.object.content.blank? && render(partial: 'compaigns/followups/followup', locals: { followup_count: followup_count, business: business }) || f.object.content %>
    <%= f.text_area :content, placeholder: 'Followup mail', value: sanitize(default_content), class: 'form-control', rows: 10, required: ( !f.object.sent ) , readonly:  ( f.object.sent ) %>
  </div>

  <div class="mb-3">
    <label class="form-label text-muted">Send followup at</label>
    <%= f.datetime_field :sent_at, class: 'form-control', required: ( !f.object.sent ) , readonly:  ( f.object.sent ) %>
  </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/compaigns/edit.html.erb
<div class="d-flex flex-column p-5 m-auto w-70rem mt-5  shadow">
  <h3 class="text-center">Edit compaign</h3>

  <%= form_with(model:@compaign, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } ) do |form| %>
    <%= render "shared/error_messages", object: @compaign %>

    <div class="row">
      <div class="col">
        <div class="mb-3">
          <label for="business_id" class="form-label text-muted"><%= form.label :business_id %></label>
          <%= form.text_field :business_id, value: @compaign.business.name, class: 'form-control', readonly: true %>
        </div>
      </div>

      <div class="col">
        <div class="mb-3">
          <label for="business_email_id" class="form-label text-muted"><%= form.label :business_email_id %></label>
          <%= form.text_field :business_email, value: @compaign.business_email.email, class: 'form-control', readonly: true %>
        </div>
      </div>

      <div class="col">
        <div class="mb-3">
          <%= form.label :service, class: 'form-label text-muted' %><br />
          <%= form.text_field :serivce_id, value: @compaign.service.name, class: 'form-control', readonly: true %>
        </div>
      </div>
    </div>

    <%= form.fields_for :followups do |followup_fields| %>
      <%= render "followup_form", f: followup_fields, followup_count: @compaign.followups.size, business: @compaign.business %>
    <% end %>

    <template data-nested-form-target="template">
      <%= form.fields_for :followups, @compaign.followups.new, child_index: 'NEW_RECORD' do |followup_fields| %>
        <%= render "followup_form", f: followup_fields, followup_count: @compaign.followups.size, business: @compaign.business %>
      <% end %>
    </template>
    <div data-nested-form-target="target"></div>

    <button type="button" data-action="nested-form#add", class="btn border btn-light">Add new followup</button>

    <div class="mb-3">
      <label class="form-label text-muted">Schedule compaign</label>
      <%= form.datetime_field :scheduled_at, class: 'form-control', readonly: true %>
    </div>

    <div class="text-center">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>

  <br>

  <div>
    <%= link_to "Show this compaign", @compaign %> |
    <%= link_to "Back to business", @compaign.business %>
  </div>
</div>

app/views/compaigns/new.html.erb
<div class="d-flex flex-column p-5 m-auto w-70rem mt-5 shadow">
  <h3 class="text-center">Send Emails</h3>

  <div class="text-start">
    <%= form_with(model: @compaign, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }) do |form| %>
      <%= render "shared/error_messages", object: @compaign %>

      <div class="row">
        <div class="col">
          <div class="mb-3">
            <label for="business_id" class="form-label text-muted"><%= form.label :business_id %></label>
            <%= form.text_field :business_id, value: @business.name, class: 'form-control', readonly: true %>
          </div>
        </div>

        <div class="col">
          <div class="mb-3">
            <%= form.label :business_email, class: 'form-label text-muted' %><br />
            <%= form.select :business_email_id, @business.business_emails.all.pluck(:email, :id), {}, class: "form-select" %>
          </div>
        </div>

        <div class="col">
          <div class="mb-3">
            <%= form.label :service, class: 'form-label text-muted' %><br />
            <%= form.select :service_id, @business.services.all.pluck(:name, :id), {}, class: "form-select" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <div class="mb-3">
            <%= form.label :title, class: 'form-label text-muted' %><br />
            <%= form.select :title_id, Title.all.pluck(:name, :id), {}, class: "form-select" %>
          </div>
        </div>

        <div class="col">
          <div class="mb-3">
            <%= form.label :platform, class: 'form-label text-muted' %><br />
            <%= form.select :platform_id, Platform.all.pluck(:name, :id), {}, class: "form-select" %>
          </div>
        </div>

        <div class="col">
          <div class="mb-3">
            <%= form.label :country, class: 'form-label text-muted' %><br />
            <%= form.select :country_id, Country.all.pluck(:name, :id), {}, class: "form-select" %>
          </div>
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :email_subject, class: 'form-label text-muted' %><br />
        <%= form.text_field :email_subject, class: 'form-control', required: true %>
      </div>

      <div class="mb-3">
        <%= form.label :email_body, class: 'form-label text-muted' %><br />
        <%= form.text_area :email_body, size: "70x10", class: 'form-control', required: true %>
      </div>

      <template data-nested-form-target="template">
        <%= form.fields_for :followups, Followup.new, child_index: 'NEW_RECORD' do |followup_fields| %>
          <%= render "followup_form", f: followup_fields, followup_count: @compaign.followups.size, business: @business %>
        <% end %>
      </template>
      <div data-nested-form-target="target"></div>

      <button type="button" data-action="nested-form#add", class="btn border btn-light">Add new followup</button>

      <div class="mb-3">
        <label class="form-label text-muted">Upload CSV File:</label>
        <%= form.file_field :csv_file, placeholder: 'Email address...', class: 'form-control', required: true %>
      </div>

      <div class="mb-3">
        <label class="form-label text-muted">Schedule compaign</label>
        <%= form.datetime_field :scheduled_at, class: 'form-control', required: true %>
      </div>

      <div class="text-center">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <%= link_to "Back to business", @business %>
</div>

app/views/compaigns/show.html.erb
<div class="p-5">
  <div class="d-flex flex-wrap justify-content-between">
    <% @compaign.followups.each_with_index do |followup, i| %>
      <div class="border border-2 w-16rem">
        <div class="fs-5 fw-semibold bg-light p-2"><%= num_to_text(i+1).titlecase %> Follow-up</div>
        <div class="p-2"><%= followup.sent_at.strftime("On %A %d-%b-%Y") %></div>
        <div class="p-2"><%= display_followup_status(followup, i+1 ) %></div>
      </div>
    <% end %>
  </div>

  <div class="d-flex flex-wrap bg-light justify-content-between p-3 mt-5" >
    <div class="fw-semibold">Leads (<%= @compaign.leads_count %>)</div>
    <div><%= link_to "Edit this compaign", edit_compaign_path(@compaign) %></div>
    <div><%= button_to "Destroy this compaign", @compaign, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-danger" %></div>
  </div>

  <div class="row m-0 py-1 border-bottom bg-light fw-semibold mt-3">
    <div class="col">Name</div>
    <div class="col">Email</div>
    <div class="col">Email Subject</div>
    <div class="col">Status</div>
  </div>
  <% @compaign.processed_leads.includes(:lead) .each do |p_lead| %>
    <div class="row py-1 border-bottom m-0">
      <div class="col"><%= p_lead.lead.name %></div>
      <div class="col"><%= p_lead.lead.email %></div>
      <div class="col"><%= p_lead.email_subject %></div>
      <div class="col"><%= p_lead.active ? 'Active' : 'Inactive' %></div>
    </div>
  <% end %>
</div>

<div>
  <%= link_to "Back to business", @compaign.business %>
</div>